apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleetman
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dan1dan12345678/Helm_charts.git'
    targetRevision: HEAD
      #    path: path/to/your/k8s/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

