apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: {{ .Values.webapp.numberOfWebReplicas}}
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        # Note to deployer - add -dev at the end of here for development version
        image: {{ .Values.dockerRepoName }}/k8s-fleetman-helm-demo:v1.0.0{{ lower  if .Values.development }}-dev{{ end }}

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30081

  type: NodePort
